### ISSUE TITLE
Doesn't always keep the time in 12 hour format, gets overwritten/updated over in some cases (Firefox)

### ISSUE THREAD

**Issue by ethel-dev** [smuke/HLTV-12-Hour-Clock#1]
I get an issue of the times quickly being correctly converted to 12 hour, but then being converted back into 24 hour on this page in Firefox. May be able to work on a fix for this if you're interested.

https://www.hltv.org/events/7524/matches

**Comment by smuke** [comment]
Can you see if ebcf8fecf258ed56599e9c60b6243b6baf5349d8 fixes the issue? If you have a better solution, feel free to contribute! Thanks

**Comment by ethel-dev** [comment]
Quick work! I'm currently in my finals week so will test soon.  Looks good though, a listener should work
